name: Webinar Kit
description: Provides an ability to add Webinars on a Drupal website. Adds a Webinar Content type and a view display upcoming and past Webinars.
install:
  # Core
  - datetime
  - file
  - link
  - media
  - media_library
  - menu_ui
  - views
  # Contrib
  - field_group
  - pathauto
